public class Wuerfel {
    public int wurf(){
        return (int)(Math.random()*6) + 1;
    }
}
/*This method, named `wurf()`, generates a random integer that simulates the roll of a six-sided dice (also known as a
fair die). Let's break it down step by step:

1. `Math.random()`: This method in Java returns a random double value between 0.0 (inclusive) and 1.0 (exclusive).

2. `(Math.random() * 6)`: By multiplying the random double value generated by `Math.random()` by 6, you get a random
 double value between 0.0 (inclusive) and 6.0 (exclusive).

3. `(int)(Math.random() * 6)`: Casting this value to an integer truncates the decimal part, giving you a random
integer between 0 (inclusive) and 5 (inclusive).

4. `(int)(Math.random() * 6) + 1`: By adding 1 to the result, the range becomes 1 (inclusive) to 6 (inclusive),
which aligns with the sides of a six-sided die.

5. `return (int)(Math.random() * 6) + 1;`: Finally, the method returns this random integer, effectively simulating
the roll of a six-sided die and giving a random number between 1 and 6 inclusive.

In summary, calling the `wurf()` method will simulate rolling a fair six-sided die and return a random number
between 1 and 6.*/